%%
disp('deleteDupsTest1')
A='abcaddeggh';
B_cor='abcdegh';
[B]=deleteDups(A);
assert( strcmp(B,B_cor)  , ...
    [ '\nYour output \nB = [' sprintf(' %s ',B)  ']\n\n' ...
      'Expected output \nB_cor = [' sprintf(' %s ',B_cor)  ']\n' ], ...
      B,B_cor);
%%
disp('deleteDupsTest2')
A='2Y6THqSrz47yrYaz8bXIYCebuOyDgt';
B_cor='2Y6THqSrz47ya8bXICeuODgt';
[B]=deleteDups(A);
assert( strcmp(B,B_cor)  , ...
    [ '\nYour output \nB = [' sprintf(' %s ',B)  ']\n\n' ...
      'Expected output \nB_cor = [' sprintf(' %s ',B_cor)  ']\n' ], ...
      B,B_cor);
%%
disp('deleteDupsTest3')
A='qxtmBWdPr3tikruG7NbWN5qPfpSmI9LzCm7SVAXm';
B_cor='qxtmBWdPr3ikuG7Nb5fpSI9LzCVAX';
[B]=deleteDups(A);
assert( strcmp(B,B_cor)  , ...
    [ '\nYour output \nB = [' sprintf(' %s ',B)  ']\n\n' ...
      'Expected output \nB_cor = [' sprintf(' %s ',B_cor)  ']\n' ], ...
      B,B_cor);
