%%
disp('SortLengthTest1')
C={ '3MCIfUd2'  ,  'pt6KMoYtCQQr'  ,  'dXD0MI6jje'};
B_cor={ 'pt6KMoYCQr'    'dXD0MI6je'    '3MCIfUd2'};
[B]=SortLength(C);
assert( strcmp(B{1},B_cor{1}) &&  strcmp(B{end},B_cor{end}) , ...
    [ '\nYour output \nB{1} = [' sprintf(' %s ',B{1})  ']\n' ...
    'B{end} = [' sprintf(' %s ',B{end})  ']\n\n' ...
      'Expected output \nB_cor{1} = [' sprintf(' %s ',B_cor{1})  ']\n'  ...
      'B_cor{end} = [' sprintf(' %s ',B_cor{end})  ']\n' ], ...
      B{1},B{end},B_cor{1},B_cor{end});
%%
disp('SortLengthTest2')
C={ 'KXowiUhygEInTlIByQYfKcRGRrudV66thlLPpE2C' ,   'rJpG49CyRKouWqLxPmcY'  ,  'zcxkA2R5vQFapomoacOIpCCLqlotZ4'};
B_cor={ 'KXowiUhygEInTlBQYfcRGrudV6tLPp2C'  ,  'zcxkA2R5vQFapomOICLqltZ4' ,   'rJpG49CyRKouWqLxPmcY'};
[B]=SortLength(C);
assert( strcmp(B{1},B_cor{1}) &&  strcmp(B{end},B_cor{end}) , ...
    [ '\nYour output \nB{1} = [' sprintf(' %s ',B{1})  ']\n' ...
    'B{end} = [' sprintf(' %s ',B{end})  ']\n\n' ...
      'Expected output \nB_cor{1} = [' sprintf(' %s ',B_cor{1})  ']\n'  ...
      'B_cor{end} = [' sprintf(' %s ',B_cor{end})  ']\n' ], ...
      B{1},B{end},B_cor{1},B_cor{end});
  
%%
disp('SortLengthTest3')
C={ 'Wr17zRh91qUWWE39G1RVjYIbnO7zIW'  ,  'XdwZ1ndhL9D44cmWbOWBjPip2iI4MToApXw2wQJh'  ,  'rSKP388K1UVLD4fzPViU'};
B_cor={'XdwZ1nhL9D4cmWbOBjPip2IMToAQJ'  ,  'Wr17zRh9qUE3GVjYIbnO'  ,  'rSKP381UVLD4fzi'};
[B]=SortLength(C);
assert( strcmp(B{1},B_cor{1}) &&  strcmp(B{end},B_cor{end}) , ...
    [ '\nYour output \nB{1} = [' sprintf(' %s ',B{1})  ']\n' ...
    'B{end} = [' sprintf(' %s ',B{end})  ']\n\n' ...
      'Expected output \nB_cor{1} = [' sprintf(' %s ',B_cor{1})  ']\n'  ...
      'B_cor{end} = [' sprintf(' %s ',B_cor{end})  ']\n' ], ...
      B{1},B{end},B_cor{1},B_cor{end});
  
  
