t<-seq(0,8,by=0.05)
pdf("alias.pdf")
plot(t, cos(2*pi*t/4), axes=F, type="l", ylab=expression(y[t]), xlab="Time", main="Aliasing")
axis(1, at=c(1,2,3,4,5,6,7))
axis(1)
axis(2)
box()
lines(t,cos(2*pi*t*3/4),lty="dashed", type="l")
abline(h=0)
points(x<-c(0:8), y=cos(2*pi*c(0:8)/4),pch=19)
dev.off()
