mort<-scan("cmort.dat")

pdf("filter.pdf")
plot(mort,xlab="Week",ylab="Mortality", main="Cardiovascular Mortality in LA, with Moving Average Filter")
ma5<-filter(mort,sides=2,rep(1,5)/5)
ma53<-filter(mort,sides=2,rep(1,53)/53)
lines(ma5, col="red")
lines(ma53, col="blue")
legend("topright", c("monthly","yearly"), lty=c(1,1), col=c("red","blue"))
dev.off()

pdf("mort.pdf")
plot(mort,xlab="Week",ylab="Mortality", main="Cardiovascular Mortality in LA")
dev.off()

pdf("kernel_normal.pdf")
t<-1:length(mort)
plot(t,mort,xlab="Week",ylab="Mortality", main="Cardiovascular Mortality in LA, with Normal Kernel Smoothing")
lines(ksmooth(t,mort, "normal", bandwidth=10), col="red")
lines(ksmooth(t,mort, "normal", bandwidth=104), col="blue")
legend("topright", c("monthly","yearly"), lty=c(1,1), col=c("red","blue"))
dev.off()

pdf("kernel_u.pdf")
t<-1:length(mort)
plot(t,mort,xlab="Week",ylab="Mortality", main="Cardiovascular Mortality in LA, with Uniform Kernel Smoothing")
lines(ksmooth(t,mort, "box", bandwidth=10), col="red")
lines(ksmooth(t,mort, "box", bandwidth=104), col="blue")
legend("topright", c("monthly","yearly"), lty=c(1,1), col=c("red","blue"))
dev.off()

pdf("neighbor.pdf")
plot(t,mort,xlab="Week",ylab="Mortality", main="Cardiovascular Mortality in LA, with Nearest Neighbor")
lines(supsmu(t,mort,span=0.01),col="red")
lines(supsmu(t,mort,span=0.5),col="blue")
legend("topright", c("monthly","yearly"), lty=c(1,1), col=c("red","blue"))
dev.off()
