%%
disp('romanNumeralTest1')
x=7;
y_cor='VII';
y=romanNumeral(x);
assert( strcmp(y,y_cor)  , ...
    [ '\nYour output \ny =' y '\n\n' ...
      'Expected output \ny_cor ='  y_cor '\n' ], ...
      y,y_cor);
%%
disp('romanNumeralTest2')
x=38;
y_cor='XXXVIII';
y=romanNumeral(x);
assert( strcmp(y,y_cor)  , ...
    [ '\nYour output \ny =' y '\n\n' ...
      'Expected output \ny_cor ='  y_cor '\n' ], ...
      y,y_cor);
%%
disp('romanNumeralTest3')
x=469;
y_cor='CDLXIX';
y=romanNumeral(x);
assert( strcmp(y,y_cor)  , ...
    [ '\nYour output \ny =' y '\n\n' ...
      'Expected output \ny_cor ='  y_cor '\n' ], ...
      y,y_cor);
%%
disp('romanNumeralTest4')
x=3847;
y_cor='MMMDCCCXLVII';
y=romanNumeral(x);
assert( strcmp(y,y_cor)  , ...
    [ '\nYour output \ny =' y '\n\n' ...
      'Expected output \ny_cor ='  y_cor '\n' ], ...
      y,y_cor);
%%
disp('romanNumeralTest5')
x=4000;
y_cor='';
y=romanNumeral(x);
assert( isempty(y)  , ...
    [ '\nYour output \ny =' y '\n\n' ...
      'Expected output \ny_cor ='  y_cor '\n' ], ...
      y,y_cor);
